# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_guitarchord_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarchord',
            name='a_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='a_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='b_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='b_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='d_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='d_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='g_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='g_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='high_e_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='high_e_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='low_e_string',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='low_e_string_finger',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarchord',
            name='name',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('Db', 'Db'), ('D', 'D'), ('D#', 'D#'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('Gb', 'Gb'), ('G', 'G'), ('G#', 'G#'), ('Ab', 'Ab'), ('A ', 'A'), ('A#', 'A#'), ('Bb', 'Bb'), ('B', 'B'), ('A/C#', 'A/C#'), ('A/E', 'A/E'), ('A/F', 'A/F'), ('A/G', 'A/G'), ('A/G#', 'A/G#'), ('Am/C', 'Am/C'), ('Am/E', 'Am/E'), ('Am/F', 'Am/F'), ('Am/F#', 'Am/F#'), ('Am/G', 'Am/G'), ('Am/G#', 'Am/G#'), ('C/E', 'C/E'), ('C/F', 'C/F'), ('C/G', 'C/G'), ('D/A', 'D/A'), ('D/B', 'D/B'), ('D/Bb', 'D/Bb'), ('D/C', 'D/C'), ('D/F#', 'D/F#'), ('E/B', 'E/B'), ('E/C#', 'E/C#'), ('E/D', 'E/D'), ('E/D#', 'E/D#'), ('E/F', 'E/F'), ('E/F#', 'E/F#'), ('E/G', 'E/G'), ('E/G#', 'E/G#'), ('Em/B', 'Em/B'), ('Em/C#', 'Em/C#'), ('Em/D', 'Em/D'), ('Em/D#', 'Em/D#'), ('Em/F', 'Em/F'), ('Em/F#', 'Em/F#'), ('Em/G', 'Em/G'), ('Em/G#', 'Em/G#'), ('F/A', 'F/A'), ('F/C', 'F/C'), ('F/D', 'F/D'), ('F/D#', 'F/D#'), ('F/E', 'F/E'), ('F/G', 'F/G'), ('Fm/C', 'F/C'), ('G/B', 'G/B'), ('G/D', 'G/D'), ('G/E', 'G/E'), ('G/F', 'G/F'), ('G/F#', 'G/F#'), ('', '')], default='', max_length=100),
        ),
    ]
